title: Toolkit
email: utml.cds@utoronto.ca
description: Digital scholarship resources and documentation for research and teaching, developed by the University of Toronto Mississauga Library. # this means to ignore newlines until "baseurl:"
baseurl: "/toolkit" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: utmlibrary
github_username:  utmlibrary
instagram_username: utmlibrary

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation
header_pages:
  - workshops.markdown
  - contributors.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
